### ISSUE TITLE
Setup instructions don't work on Windows (Was: ModuleNotFoundError: No module named 'amberelectric')

### ISSUE THREAD

**Issue by TaylorWoods1** [GrahamLea/amber-usage-summary#1]
@GrahamLea any thoughts on the above error?

**Comment by GrahamLea** [comment]
Gonna need more info on where/when this is happening.

Have you follow the [setup steps in the README](https://github.com/GrahamLea/amberelectic-api-tools#setup), for example?

**Comment by TaylorWoods1** [comment]
Thanks for getting back so quick!

i have.  it reports the following error on the first line of setup:

python3.9  -m  venv  venv
  File "C:\Users\taylo************", line 1
    python3.9  -m  venv  venv
           ^
SyntaxError: invalid syntax

**Comment by TaylorWoods1** [comment]
python3.9 : The term 'python3.9' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ python3.9 -m venv venv
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (python3.9:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by GrahamLea** [comment]
Ah, okay. It seems like my instructions presume a Linux-like environment. I haven't tested with Windows, sorry.

So, "python3.9" is the name of the Python executable on Linux, which is automatically placed in the path when Python is installed.

Can you run `python.exe -V` and do you get a Python version number printed?

**Comment by TaylorWoods1** [comment]
python3.10 and yes i tried changing the 9 to a 10 :) haha

**Comment by TaylorWoods1** [comment]
# C:\Users\taylo\AppData\Local\Programs\Python\Python310\

**Comment by TaylorWoods1** [comment]
>>> python310 -m venv venv
  File "<stdin>", line 1
    python310 -m venv venv
                           ^^^^
SyntaxError: invalid syntax

**Comment by GrahamLea** [comment]
Okay, I think you should be able to just run `python -m  venv  venv` then, and it'll work.

**Comment by GrahamLea** [comment]
Actually, the next line probably isn't going to work either. 'source' is a pretty Linux-y thing.
`source  ./venv/bin/activate`
Let me find how that works on Windows...

**Comment by TaylorWoods1** [comment]
yep you pre-empted the next issue! thanks for your help

**Comment by GrahamLea** [comment]
Okay, it seems if you're running in `cmd.exe`, you'll want to run:
```.\Scripts\activate.bat```

Or if you're using PowerShell, you'll want to run:
```.\Scripts\Activate.ps1```

After that I *think* everything else should be architecture independent, but let me know if that's not the case.

**Comment by TaylorWoods1** [comment]
Ive tried using both cmd and powershell and Spyder. all similar responses.


.\Scripts\Activate.ps1 : The term '.\Scripts\Activate.ps1' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ .\Scripts\Activate.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Scripts\Activate.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by GrahamLea** [comment]
Oh, I think I stuffed up. It's `.\venv\Scripts\...`
I left out the `venv`, sorry.

Also, it's apparently different for "PowerShell Core", if that's what you're using:
```./venv/bin/Activate.ps1```

**Comment by TaylorWoods1** [comment]
this worked in Powershell 
.\venv\Scripts\Activate.bat

**Comment by TaylorWoods1** [comment]
so
python -m venv venv
.\venv\Scripts\Activate.bat

**Comment by GrahamLea** [comment]
Thanks for persisting, Taylor!
It's been a while since I've Windowsed, and never with Python.

Would you mind helping me out by posting a directory listing of `.\venv` and `.\venv\Scripts`?
That way I'll know exactly what venv has installed, and I'll be able to update the README for future Windows users.

**Comment by TaylorWoods1** [comment]
C:\Users\taylo\AppData\Local\Programs\Python\Python310\Lib\venv

**Comment by TaylorWoods1** [comment]
Directory: C:\Users\taylo\AppData\Local\Programs\Python\Python310\Lib\venv


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         1/02/2022   1:31 PM                scripts
d-----         1/07/2022  10:24 AM                __pycache__
-a----        17/01/2022   2:25 PM          23723 __init__.py
-a----        17/01/2022   2:25 PM            155 __main__.py

**Comment by TaylorWoods1** [comment]
Directory: C:\Users\taylo\AppData\Local\Programs\Python\Python310\Lib\venv\scripts


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         1/02/2022   1:31 PM                common
d-----         1/02/2022   1:31 PM                nt
d-----         1/02/2022   1:31 PM                posix


PS C:\Users\taylo\AppData\Local\Programs\Python\Python310\Lib\venv\scripts>

**Comment by TaylorWoods1** [comment]
this what youre after?

**Comment by GrahamLea** [comment]
Sorry, I don't think that's what I was asking for.
I think, in the directory where you've cloned this repo to (`amberelectic-api-tools`), there should be a `venv` directory there, and that is the one I was hoping to have a listing of, as well as its Scripts subdirectory.
(I am assuming you haven't cloned this repo into `C:\Users\taylo\AppData\Local\Programs\Python\Python310\Lib`?)

**Comment by TaylorWoods1** [comment]
Directory: C:\Users\taylo\OneDrive\Desktop\amberelectic-api-tools-main\venv


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         1/07/2022  10:24 AM                Include
d-----         1/07/2022  10:24 AM                Lib
d-----         1/07/2022  10:25 AM                Scripts
-a----         1/07/2022  11:44 AM            119 pyvenv.cfg

**Comment by TaylorWoods1** [comment]
Directory: C:\Users\taylo\OneDrive\Desktop\amberelectic-api-tools-main\venv\Scripts


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         1/07/2022  11:44 AM           2104 activate
-a----         1/07/2022  11:44 AM           1033 activate.bat
-a----         1/07/2022  11:44 AM          20571 Activate.ps1
-a----         1/07/2022  11:44 AM            393 deactivate.bat
-a----         1/07/2022  10:25 AM         106415 pip.exe
-a----         1/07/2022  10:25 AM         106415 pip3.10.exe
-a----         1/07/2022  10:25 AM         106415 pip3.exe
-a----         1/07/2022  11:44 AM         263056 python.exe
-a----         1/07/2022  11:44 AM         251792 pythonw.exe

**Comment by GrahamLea** [comment]
Perfect. Thanks!

**Comment by TaylorWoods1** [comment]
side question, using the api key as a saved file. does it matter if its .txt or should it be something else?

**Comment by GrahamLea** [comment]
It should just be called `apitoken`, with no extension. Format-wise, yes it's just text in the file.

**Comment by TaylorWoods1** [comment]
is this what it should look like then?
python  amber_usage_summary.py  --api-token   apitoken >  my_amber_usage_data.csv

**Comment by TaylorWoods1** [comment]
it doesnt seem to work when i put in apitoken instead of the actual api Token each time.

**Comment by GrahamLea** [comment]
If you've put your API token into a file called just `apitoken`, then you shouldn't use the `--api-token apitoken` part in the command. Just `python amber_usage_summary.py > my_amber_usage_data.csv` should work.

**Comment by TaylorWoods1** [comment]
excellent
thankyou!
