### ISSUE TITLE
Half hourly usage stats

### ISSUE THREAD

**Issue by TaylorWoods1** [GrahamLea/amber-usage-summary#2]
Hey Graham,

another question for you. How is easiest to get a csv of the half hourly usage / demand data?

**Comment by GrahamLea** [comment]
Hey Taylor.

I don't have a tool that does that at the moment.

If you have some basic programming skills, or know someone charitable who does, you should be able to make a new script based off [`amber_usage_summary.py`](https://github.com/GrahamLea/amberelectic-api-tools/blob/cc6f9793c7c329bdb6a82ca44bf84684eaec1cfe/amber_usage_summary.py#L67) that does what you want. That script already does pretty much everything you want - streams all the usage data for a date query, and writes CSV output. It just has extra logic in it between those two steps to summarise the data by date. It shouldn't take too much effort to create a new script (`amber_usage_dump.py` ?) that simply prints the data as a CSV as it is downloaded.

Let me know if you need any help. If you come up with something and want to contribute it back, that'd be great!
